# Generated by Django 2.2.4 on 2019-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('complain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
